apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytriotaskflaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytriotaskflaskapp # must be the same value as the label in the template
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mytriotaskflaskapp # this label is assigned to each pod in the set
    spec:
      containers:
      - name: mytriotaskflaskapp
        image: chrisreeves1/mytriotaskflaskapp:2.0
        ports:
        - containerPort: 5000
